version: "3.8"

services:
  go-api:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: go-api
    depends_on:
      - postgres
    restart: always
    ports:
      - "5000:5000"
